id: P3F2664E1
initial_creation_type: ocr
source_metadata:
  volumes:
    058fb5c09b634802af3a1dc3870babec:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་རྡོ་རྗེ་གཅོད་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1682
      volume_number: 56
